name: Deploy Quiz App to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          # These secrets can be safely reused
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          
          # This uses the NEW, specific secret for this project
          key: ${{ secrets.SSH_PRIVATE_KEY_QUIZAPP }} 
          
          script: |
            echo "Deploying Quiz App..."
            cd /var/www/quiz.serveris.live
            git pull origin main
            echo "Quiz App deployment finished!"