# Name of the workflow
name: Deploy Quiz App to Azure

# Trigger: Run this workflow on every push to the 'main' branch
on:
  push:
    branches: [ main ]

# Jobs to be executed
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out the repository code so the workflow can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: SSH into the server and deploy
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.quizdeploykey }}
          script: |
            echo "Starting deployment..."
            cd /var/www/quiz.serveris.live
            git pull origin main
            echo "Deployment finished!"